dist: trusty
sudo: required

addons:
  sonarqube:
    token:
      secure: "ocyQIwTL9ocY89/gVCMXWEcBuIfgz5S29XAByggVLV2bgyDIGWBLMuNNbx9nS2ZQCxNxTHyX0aOXph4f9FE7qdNuAoZ2aFlAYTOzoIITRxZU3aS4YyMPX2WQKl55fAvDygnFCxPrrjZUSUZqt4AHdvHG27yVb3RGOLsBc/wqKUFj8v+8378Ffl81Vd2tQJr8eBgf57Wled2OkPrKQOJMS4yJZNUoguL9uVPz37KkIkvHHX4iDGETdyIOILv432GwnTx9o3aj6aBpnZ9IBf1w9lOMyIWB/H9e1vkqYmvLBmv2IONjOWQLrQJREdZvXglSnqmIyLMwvnXmk0afhyOWqbrYV+VZf5EV95OHYzR1JLuYxWELvvZLl7I7p5GgRM7D6lK6F5sep96Vg+y/5ClOpFCZbT1IGELCr4EG9Bi/3EmurEVu7yMmUnKCAXCPryj/CZHy17fzIYt4nPiz7dxJtObuU9VsLOZra0PGNsYyZabIRJCt25cyYT19Hr+XkP3u+yRCUZ+p4TYZWsHXDTFiLq4nnloP6wXsF3ufqvso6lIWHODbj2fz8so7q/zfk8ZI0xLvGdq26fKXlc2sF8IJ1qCFWPizzTvU2/0yE1l8u2NKW3iVdkHTDYja+RFZSU1qE2u0WrylH4c6N67+UiyyCKqR9BNmrpj9KFo+XM2Ctd4="

jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email: false
